name: test issues

env:
  GH_TOKEN: ${{ secrets.ABC_TOKEN }}

on:
  issues:

jobs:
  test-issues-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "test-issues-Actions 111"
      - run: ls && echo "--------"
      - run: ./shell.sh


