
name: print-event

on:
  discussion:
  discussion_comment:
#  issues:
#  issue_comment:
#  pull_request:
#  pull_request_review:
#  pull_request_review_comment:


jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT